### ISSUE TITLE
Hart chart size relative to Main div

### ISSUE THREAD

**Issue by quartertone** [visiontherapy/visiontherapy.github.io#4]
use container queries

https://moderncss.dev/container-query-units-and-fluid-typography/

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_size_and_style_queries

**Comment by visiontherapy** [comment]
Mobile version needs to be 3x3cm (1.25x1.25in)

Large version 15x18cm

**Comment by quartertone** [comment]
Done.
Used transform: scale
